Manifest draft
it-highlight/manifest pull request #1
Opened 2020-05-18 16:58 UTC by sd1ver

2020-05-18 19:10 UTC, Primetalk approved these changes
Добавил комментарии для обсуждения.

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +5. Фокус на культуре и ценностях, а не на конкретных паттернах, которые устаревают со временем.
Мне этот пункт не очень понятен. Хорошо бы обсудить.

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +6. Борьба с ценностями функционеров, для которых важен результат в любом виде,  путем просвещения и распространения "правильных" идей.
Было бы неплохо все двойные пробелы общим поиском заменить на одинарные.

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +6. Борьба с ценностями функционеров, для которых важен результат в любом виде,  путем просвещения и распространения "правильных" идей.
Предлагаю дополнить.
> Важен не только сиюминутный результат, но и другие эффекты 
- гибкость, поддерживаемость в будущем (определяет жизнеспособность системы);
- влияние на стиль команды (подобное рождает подобное).

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +   * Студенты.популяризация профессии - инженерные ценности для студентов и “увлеченных”.
"." между словами

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +3. Школьники: Пропаганда профессии для школьников.
на уровень ниже. Входит в "не программисты".
После ":" не надо писать с большой буквы.

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +2. Видеозаписи дискуссий, логи, стенограммы и протоколы.
Мы, кажется, неплохо стартовали с видео-записями - https://www.youtube.com/channel/UC9iHTPwwBnYYaUsLywMD1sQ :)

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +3. Постоянное стремление к совершенству инженерных навыков.
Может, "Постоянное совершенствование и оттачивание инженерных навыков."?

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +4. Сообщество борется с восприятием инженерии в целом (и программирования в частности) как ремесла, противостоит принципу "лишь бы работало" и прочим недальновидным безответственным подходам к разраб
Может, "программирования (и инженерии в целом)"?

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +   * “Образование делает умного человека чуточку мудрее, а дурака неизмеримо опаснее”(C).
Кавычки по всему тексту желательно сделать одинаковыми. Либо машинописные ", либо ёлочки «».
(Copyright © - тоже можно вставить символом.)

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +   * Мы в основном ведем речь про хороший, понятный, легко читаемый и поддерживаемый код. Про саму эту идею.
Может, поискать другое место для этой фразы?

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +6. Ценности > культура > качество > результат.
Хорошо бы расшифровать `>`. Например, "ценности важнее культуры", или "ценности в лаконичной и абстрактной форме выражают то, к чему стремится группа людей, в то время как культура в неконкретной форме описывает сложившиеся практики, отношения."

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +7. Для нас качество + ценности + компетенции важнее сиюминутного результата/ выгоды.
"результата/" можно убрать.

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +8. Главным оппонентом нашего message выступает все “бескультурное сообщество”, люди, пренебрегающие долговременными ценностями в угоду сиюминутной выгоды.
"message" -> "движения"
"в угоду... выгоде" - немного тафтологично звучит. Может, "в угоду сиюминутным потребностям"?

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +9. Мы не допускаем безапелляционных суждений, понимая, что мир сложен и не может быть сведён к чёрному и белому.
:)
Ещё бы так сформулировали:
"Мы категорически не допускаем безапелляционных суждений... За каждое безапелляционное суждение - немедленный расстрел без права обжалования" :D

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +   * Контибьютеры - люди полностью разделяющие ценности и желающие вносить свой вклад
Контибьютеры - калька с английского. Давайте попробуем найти русское слово? "Товарищи" :)
- "активные участники сообщества" - люди, принимающие участие в деятельности сообщества, участвующие в выработке ценностей (как мне кажется, не обязательно разделять все-все ценности. Должен быть определённый плюрализм.);
- "сторонники" - люди, в целом разделяющие ценности, но не принимающие активного участия в деятельности.

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +2. Независимость от коммерческих организаций - мы не защищаем и не продвигаем интересы каких-либо коммерческих организаций.
... в настоящее время.
Возможно, коммерческие организации, заинтересованные в деятельности сообщества, будут становится участниками или оказывать поддержку сообществу, его деятельности и целям на благотворительной основе. При этом сообщество не может быть связано какими-либо обязательствами с такими коммерческими организациями за исключением предоставления возможности этим организациям публично объявлять о своём участии.

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +1. Открытость, сообщество состоит из нескольких частей:
Все пункты должны быть согласованы с точки зрения русского языка. А именно, если это часть предложения, то должно быть явное начало и двоеточие. В противном случае, каждый пункт должен представлять собой самостоятельное предложение.

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +3. Не привязана к компании.
Сообщество может быть оформлено как некоммерческая организация, не аффилированная с другими компаниями.

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +   * Мы готовы нести свою миссию во все компании и ни в коем случае не замыкаемся на одной. Только всем.
"нести миссию"-

> Деятельность сообщества должна распространяться на всех разработчиков, независимо от той компании, где они работают.

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +4. Профессиональное сообщество.
Организация формируется по принципу профессионального сообщества.

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +5. Бескорыстность: деятельность сообщества не направлена на получение материальных выгод
В конце каждого пункта - точка.

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +   * Обсуждение в рамках сообщества иных вопросов не приветствуется
"...иных вопросов, таких как погода, политика, спорт, не приветствуется; Такие вопросы лучше обсуждать в отдельных чатах или на других площадках."

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +   * В частности является недопустимой политическая, религиозная или какая-либо другая пропаганда и пропаганда какой-либо дискриминации.
запятые:
> В частности, является недопустимой политическая, религиозная или какая-либо другая пропаганда, а также пропаганда какой-либо дискриминации.

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +
Вводное предложение:
> Цели сообщества достигаются, например, такими средствами:

2020-05-18 19:10 UTC, Primetalk commented on readme.md
> +1. Конструктивная дискуссия по различным спорным темам
"." в конце каждого пункта.

2020-05-19 15:32 UTC, nolequen requested changes

2020-05-19 15:32 UTC, nolequen commented on readme.md
> +5. Фокус на культуре и ценностях, а не на конкретных паттернах, которые устаревают со временем.
Поддерживаю. Как цель это не выглядит.

2020-05-19 15:32 UTC, nolequen commented on readme.md
> +6. Борьба с ценностями функционеров, для которых важен результат в любом виде,  путем просвещения и распространения "правильных" идей.
> Предлагаю дополнить.

Тогда этот список можно долго продолжать.

2020-05-19 15:32 UTC, nolequen commented on readme.md
> +2. Расширение внутренней команды (группы контрибьюторов). Такое расширение необходимо для поддержания сообщества, т.к. всегда присутствует противоположное явление - уход людей из сообщества по разным
Мне кажется, что пояснять цели здесь не обязательно.

2020-05-19 15:32 UTC, nolequen commented on readme.md
> +    2. Следует учитывать, что бывает, что группа людей, разделяющих общую ценность “качества”, надолго застревает на частностях, в споре о выборе конкретного подхода.
Не совсем понимаю, почему это относится к целям.

2020-05-19 15:32 UTC, nolequen commented on readme.md
> +   * Студенты.популяризация профессии - инженерные ценности для студентов и “увлеченных”.
Тут бы вообще формулировку подправить...

2020-05-19 15:32 UTC, nolequen commented on readme.md
> +   * Проблема выбора для молодых людей, которые пока не осознают ценности профессии.
Не совесм ясно, какую смысловую нагрузку несет это предложение.

2020-05-19 15:32 UTC, nolequen commented on readme.md
> +3. Школьники: Пропаганда профессии для школьников.
> Пропаганда профессии для школьников.

лучше в цели перенести

2020-05-19 15:32 UTC, nolequen commented on readme.md
> +4. Блог.
по-моему, это то же самое, что и публикации. нет?

2020-05-19 15:32 UTC, nolequen commented on readme.md
> +   * Под высокой инженерной культурой мы понимаем ответственный подход к разработке, стремление внедрять и использовать наилучшие практики, стремление к чистому коду, минимизация ошибок.
может быть совместить?

> Высокая инженерная культура, под которой мы понимаем...

2020-05-19 15:32 UTC, nolequen commented on readme.md
> +   * “Образование делает умного человека чуточку мудрее, а дурака неизмеримо опаснее”(C).
а зачем вообще копирайт и кавычки?

2020-05-19 15:32 UTC, nolequen commented on readme.md
> +   * Мы в основном ведем речь про хороший, понятный, легко читаемый и поддерживаемый код. Про саму эту идею.
Плюсую. Если она вообще нужна.

2020-05-19 15:32 UTC, nolequen commented on readme.md
> +9. Мы не допускаем безапелляционных суждений, понимая, что мир сложен и не может быть сведён к чёрному и белому.
Давайте оставим просто "Мы понимаем, что мир сложен и не может быть сведён к чёрному и белому."

2020-05-19 15:32 UTC, nolequen commented on readme.md
> +1. Открытость, сообщество состоит из нескольких частей:
Думаю, что после принятия PR отдельно орагнизуем вычитку текста.

2020-05-19 15:32 UTC, nolequen commented on readme.md
> +   * Контибьютеры - люди полностью разделяющие ценности и желающие вносить свой вклад
Выше было 

> Расширение внутренней команды (группы контрибьюторов)

2020-05-19 15:32 UTC, nolequen commented on readme.md
> +2. Независимость от коммерческих организаций - мы не защищаем и не продвигаем интересы каких-либо коммерческих организаций.
По-моему, слова "независимость" и "мы не защищаем и не продвигаем интересы" уже достаточно понятны. Ни в какое другое время мы не будем продвигать чьи-то интересы.

2020-05-19 15:32 UTC, nolequen commented on readme.md
> +3. Не привязана к компании.
А может быть не оформлено. Вообще, не очень понятен смысл этого пункта в свете предыдущего.

2020-05-19 15:32 UTC, nolequen commented on readme.md
> +   * Мы готовы нести свою миссию во все компании и ни в коем случае не замыкаемся на одной. Только всем.
Не очень понятен смысл этого пункта в свете сказанного ранее.

2020-06-04 18:06 UTC, nolequen approved these changes

2020-06-04 18:06 UTC, merged